### ISSUE TITLE
Weird --atest behaviour

### ISSUE THREAD

**Issue by lesics** [nvbln/LT#18]
Last few questions give the empty question, e.g. this:
  Answered correctly: 29/658. Answered incorrectly: 628/658
  Given answers vs actual answer:
  No answer was given.
  Incorrect:

**Comment by lesics** [comment]
Also, the order right now does matter for multiple-answer questions. Example:
Given answers vs actual answer:
jim morrison vs jim morrison
ray manzarek vs robby krieger
john densmore vs ray manzarek
robby krieger vs john densmore
Incorrect:  Who were the members of The Doors?

**Comment by tomveldhuis** [comment]
I just made a PR that should have fixed this issue
