### ISSUE TITLE
Improper output of --atest --verbose.

### ISSUE THREAD

**Issue by lesics** [nvbln/LT#21]
Starting from question 643, only the empty lines are outputted, e.g:
Given answers vs actual answer:
Incorrect: 
Answered correctly: 43/658. Answered incorrectly: 600/658

**Comment by lesics** [comment]
'Given answers vs actual answer:' line is empty for all incorrect questions.

**Comment by tomveldhuis** [comment]
#24

**Comment by nvbln** [comment]
This can be closed now right? @lesics
